/**
 * DOCX Replace Round-Trip (platform-neutral)
 *
 * Byte-level marker replacement inside a .docx (ZIP) archive:
 * min-size + PK signature validation -> JSZip load -> word/document.xml
 * extraction and validation -> marker replacement via the unified engine
 * (marker-replace-engine.ts) -> write back -> regenerated bytes.
 *
 * Extracted from src/main/services/replacer.ts with the error contract
 * preserved byte-identically: same validation order, same messages, same
 * errorType mapping. The only difference: no `filePath` — this module has
 * no filesystem; the Electron wrapper (replacer.ts) re-attaches the path.
 */

import JSZip from 'jszip';
import { replaceMarkersInDocumentXml } from './marker-replace-engine';

/**
 * Error categories for the docx replace round-trip. Mirrors
 * ReplacementError['errorType'] in src/main/services/replacer.ts.
 */
export type DocxReplaceErrorType =
  | 'corrupted_file'
  | 'invalid_xml'
  | 'missing_file'
  | 'malformed_marker'
  | 'read_error'
  | 'write_error'
  | 'unknown';

/**
 * Custom error class for docx replace round-trip operations.
 * Platform-neutral twin of replacer.ts's ReplacementError, minus filePath.
 */
export class DocxReplaceError extends Error {
  public readonly cause?: Error;
  public readonly errorType?: DocxReplaceErrorType;

  constructor(message: string, cause?: Error, errorType?: DocxReplaceError['errorType']) {
    super(message);
    this.name = 'DocxReplaceError';
    this.cause = cause;
    this.errorType = errorType;
  }
}

/**
 * Replace markers inside .docx bytes and return the regenerated archive.
 *
 * @param bytes - Raw .docx file bytes (a valid ZIP archive)
 * @param values - Replacement values (key: identifier, value: replacement text)
 * @param prefix - Marker prefix
 * @returns Promise resolving with the modified .docx bytes
 * @throws DocxReplaceError if any step of the round-trip fails
 */
export async function replaceMarkersInDocxBytes(
  bytes: Uint8Array,
  values: Record<string, string>,
  prefix: string
): Promise<Uint8Array> {
  try {
    // Validate minimum file size
    if (bytes.length < 4) {
      throw new DocxReplaceError(
        `Invalid .docx file: file too small (${bytes.length} bytes)`,
        undefined,
        'corrupted_file'
      );
    }

    // Check if it's a valid ZIP file (starts with PK signature)
    if (bytes[0] !== 0x50 || bytes[1] !== 0x4b) {
      throw new DocxReplaceError(
        `Invalid .docx file: not a valid ZIP archive (missing PK signature)`,
        undefined,
        'corrupted_file'
      );
    }

    // Load the ZIP archive
    let zip: JSZip;
    try {
      zip = await JSZip.loadAsync(bytes);
    } catch (error) {
      throw new DocxReplaceError(
        `Failed to parse .docx file: corrupted or invalid ZIP archive`,
        error instanceof Error ? error : undefined,
        'corrupted_file'
      );
    }

    // Get the main document XML file
    const documentXml = zip.file('word/document.xml');
    if (!documentXml) {
      // List available files for better error message
      const availableFiles = Object.keys(zip.files).join(', ');
      throw new DocxReplaceError(
        `Invalid .docx file: word/document.xml not found. Available entries: ${availableFiles}`,
        undefined,
        'missing_file'
      );
    }

    // Extract the XML content
    let xmlContent: string;
    try {
      xmlContent = await documentXml.async('string');
    } catch (error) {
      throw new DocxReplaceError(
        `Failed to extract XML content from document.xml`,
        error instanceof Error ? error : undefined,
        'invalid_xml'
      );
    }

    // Validate XML content is not empty
    if (!xmlContent || xmlContent.trim().length === 0) {
      throw new DocxReplaceError(
        `Invalid .docx file: document.xml is empty`,
        undefined,
        'invalid_xml'
      );
    }

    // Validate XML has basic structure (must have both w:document and w:body)
    if (!xmlContent.includes('<w:document') || !xmlContent.includes('<w:body')) {
      throw new DocxReplaceError(
        `Invalid .docx file: document.xml has invalid structure (missing w:document or w:body)`,
        undefined,
        'invalid_xml'
      );
    }

    // Replace markers in the XML
    let modifiedXml: string;
    try {
      modifiedXml = replaceMarkersInDocumentXml(xmlContent, values, prefix);
    } catch (error) {
      throw new DocxReplaceError(
        `Failed to replace markers in document: ${error instanceof Error ? error.message : 'Unknown error'}`,
        error instanceof Error ? error : undefined,
        'malformed_marker'
      );
    }

    // Update the document in the ZIP
    try {
      zip.file('word/document.xml', modifiedXml);
    } catch (error) {
      throw new DocxReplaceError(
        `Failed to update document.xml in ZIP archive`,
        error instanceof Error ? error : undefined,
        'write_error'
      );
    }

    // Generate the new bytes
    try {
      return await zip.generateAsync({ type: 'uint8array' });
    } catch (error) {
      throw new DocxReplaceError(
        `Failed to generate .docx file buffer`,
        error instanceof Error ? error : undefined,
        'write_error'
      );
    }
  } catch (error) {
    if (error instanceof DocxReplaceError) {
      throw error;
    }
    throw new DocxReplaceError(
      `Failed to replace markers in document: ${error instanceof Error ? error.message : 'Unknown error'}`,
      error instanceof Error ? error : undefined,
      'unknown'
    );
  }
}
